namespace: omkar-ns

deployment:
  replicas: 2
  app: school-app
  name: school-container
  repository: omkartakalkar/school-app
  tag: v1.0.0
  port: 80

service:
  app: school-app
  protocol: TCP
  port: 80         
  targetPort: 3000
  type: LoadBalancer
