apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.deployment.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.app }}
    spec:
      containers:
        - name: {{ .Values.deployment.name }}
          image: "{{ .Values.deployment.repository }}:{{ .Values.deployment.tag }}"
          ports:
            - containerPort: {{ .Values.deployment.port }}